# _config.yml

title: "Jekyll Actions Demo" 
theme: jekyll-theme-simplex

# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one