# _config.yml

title: "Ocean Sampling Day" 
theme: minima
url: https://vliz-be-opsci.github.io
baseurl: /rocrate_test_crate

# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one